### ISSUE TITLE
Random error while registering user

### ISSUE THREAD

**Issue by Jhermyy** [juancamr/thanos-gym#3]
console:
![netbeans64_OHe1I1IexC](https://github.com/juancamr/thanos-gym/assets/89281629/e6a01b46-6e7a-4f29-b2d3-cb77c7f58baa)

db
![MySQLWorkbench_kChOWHEWQK](https://github.com/juancamr/thanos-gym/assets/89281629/acd4bcd9-e0ff-44db-ad13-21af69d0255f)
the program is able to register xd

**Comment by juancamr** [comment]
no hay error
